from pydantic import BaseModel, Field
from typing import List

class SearchPlan(BaseModel):
    """The search strategy generated by the Planner LLM."""

    search_text_datasources: List[str] = Field(
        description="Keywords to identify the correct database/service (e.g., 'sales', 'marketing', 'jira')."
    )

    search_text_tables: List[str] = Field(
        description="Technical or business keywords for tables (e.g., 'orders', 'kpi_monthly')."
    )

    search_text_columns: List[str] = Field(
        description="Keywords to identify the correct columns (e.g., 'sales', 'marketing', 'jira')."
    )

    search_text_edges: List[str] = Field(
        description="Keywords to identify the correct edges (e.g., 'sales', 'marketing', 'jira')."
    )

    search_text_metrics: List[str] = Field(
        description="Keywords to identify the correct metrics (e.g., 'sales', 'marketing', 'jira')."
    )

    search_text_synonyms: List[str] = Field(
        description="Keywords to identify the correct synonyms (e.g., 'sales', 'marketing', 'jira')."
    )

    search_text_context_rules: List[str] = Field(
        description="Keywords to identify the correct context rules (e.g., 'sales', 'marketing', 'jira')."
    )

    search_text_low_cardinality_values: List[str] = Field(
        description="Keywords to identify the correct low cardinality values (e.g., 'sales', 'marketing', 'jira')."
    )

    search_text_golden_sqls: List[str] = Field(
        description="Keywords to identify the correct golden sqls (e.g., 'sales', 'marketing', 'jira')."
    )
    

class DataSourceSelection(BaseModel):
    """The final decision on which datasource to use."""
    thought_process: str = Field(
        description="Step-by-step reasoning explaining why this datasource was chosen over others."
    )
    selected_datasource_name: str = Field(
        description="The exact name of the selected datasource found in the search results."
    )