"""initial_schema_consolidated

Revision ID: 1bcbf4bb6d12
Revises: 
Create Date: 2026-01-16 15:42:19.671559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision = '1bcbf4bb6d12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('ambiguity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('detected_ambiguity', sa.JSON(), nullable=True),
    sa.Column('user_resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('engine', sa.Enum('POSTGRES', 'BIGQUERY', 'SNOWFLAKE', 'TSQL', 'MYSQL', name='sqlenginetype'), nullable=False),
    sa.Column('context_signature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', description || ' ' || context_signature)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('generation_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('retrieved_context_snapshot', sa.JSON(), nullable=True),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_feedback', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('semantic_synonyms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.Enum('TABLE', 'COLUMN', 'METRIC', 'VALUE', name='synonymtargettype'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', term)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_synonyms_slug'), 'semantic_synonyms', ['slug'], unique=True)
    op.create_table('golden_sql',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('sql_query', sa.Text(), nullable=False),
    sa.Column('complexity_score', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', prompt_text)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golden_sql_slug'), 'golden_sql', ['slug'], unique=True)
    op.create_table('semantic_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('calculation_sql', sa.Text(), nullable=False),
    sa.Column('required_tables', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filter_condition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', name || ' ' || description)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_semantic_metrics_slug'), 'semantic_metrics', ['slug'], unique=True)
    op.create_table('table_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('datasource_id', sa.UUID(), nullable=False),
    sa.Column('physical_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('semantic_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ddl_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', semantic_name || ' ' || description)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['datasources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_nodes_slug'), 'table_nodes', ['slug'], unique=True)
    op.create_table('column_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('semantic_name', sa.String(length=255), nullable=True),
    sa.Column('data_type', sa.String(length=100), nullable=False),
    sa.Column('is_primary_key', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', semantic_name || ' ' || description || ' ' || context_note)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_nodes_slug'), 'column_nodes', ['slug'], unique=True)
    op.create_table('column_context_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', rule_text)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_context_rules_slug'), 'column_context_rules', ['slug'], unique=True)
    op.create_table('low_cardinality_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('value_raw', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('value_label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', value_label || ' ' || value_raw)", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_low_cardinality_values_slug'), 'low_cardinality_values', ['slug'], unique=True)
    op.create_table('schema_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_column_id', sa.UUID(), nullable=False),
    sa.Column('target_column_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('ONE_TO_ONE', 'ONE_TO_MANY', 'MANY_TO_MANY', name='relationshiptype'), nullable=False),
    sa.Column('is_inferred', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(description, '') || ' ' || coalesce(context_note, ''))", persisted=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('embedding_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_column_id'], ['column_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_column_id'], ['column_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_edges')
    op.drop_index(op.f('ix_low_cardinality_values_slug'), table_name='low_cardinality_values')
    op.drop_table('low_cardinality_values')
    op.drop_index(op.f('ix_column_context_rules_slug'), table_name='column_context_rules')
    op.drop_table('column_context_rules')
    op.drop_index(op.f('ix_column_nodes_slug'), table_name='column_nodes')
    op.drop_table('column_nodes')
    op.drop_index(op.f('ix_table_nodes_slug'), table_name='table_nodes')
    op.drop_table('table_nodes')
    op.drop_index(op.f('ix_semantic_metrics_slug'), table_name='semantic_metrics')
    op.drop_table('semantic_metrics')
    op.drop_index(op.f('ix_golden_sql_slug'), table_name='golden_sql')
    op.drop_table('golden_sql')
    op.drop_index(op.f('ix_semantic_synonyms_slug'), table_name='semantic_synonyms')
    op.drop_table('semantic_synonyms')
    op.drop_table('generation_traces')
    op.drop_table('datasources')
    op.drop_table('ambiguity_logs')
    # ### end Alembic commands ###
